[build]
  command = "cd frontend && yarn install && yarn build"
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
